#!/usr/bin/env bash

. test/lib/bash-setup.bash ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

#
# Skeleton for ad-hoc testiong.
#

bl64_dbg_all_enable
bl64_msg_all_enable_verbose

#
# Test Cases
#
# * Keep the source clean, do not commit test cases below this section
#

bl64_bsh_profile_path_generate
