#!/usr/bin/env bash

. bin/dev-set
. "${DEVBL_BUILD_FULL_PATH}/${DEVBL_BUILD_NAME_SINGLE}"

#
# Skeleton for ad-hoc testiong.
#

# bl64_dbg_lib_enable

#
# Test Cases
#
# * Keep the source clean, do not commit test cases below this section
#

cat "${DEVBL_TEST}/samples/url/chars-ascii-url-reserved.txt" | \
bl64_fmt_url_encode > "${DEVBL_TEST}/samples/url/chars-encoded-url-reserved.txt"

# for i in {32..126}; do
#     printf "%s\n" "$(printf "\x$(printf "%x" $i)")"
# done
