#!/usr/bin/env bash

. bin/dev-set
. "${DEV_BUILD_FULL_PATH_TEST}/${DEV_BUILD_NAME_SINGLE}"

#
# Skeleton for ad-hoc testiong.
#

# bl64_dbg_lib_enable

#
# Test Cases
#
# * Keep the source clean, do not commit test cases below this section
#

bl64_dbg_all_enable
