#!/usr/bin/env bash

. test/lib/bash-setup.bash ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

bl64_msg_all_enable_verbose

bl64_msg_show_info 'show info'
bl64_msg_show_error 'show error'
