#!/usr/bin/env bash

. bin/dev-set
. "${DEVBL_BUILD_FULL_PATH}/${DEVBL_BUILD_NAME_SINGLE}"
bl64_msg_all_enable_verbose
bl64_msg_set_output "$BL64_MSG_OUTPUT_ASCII"

bl64_msg_set_format "$BL64_MSG_FORMAT_FULL"
bl64_msg_show_error 'bl64_msg_show_error'
bl64_msg_show_warning 'bl64_msg_show_warning'
bl64_msg_show_info 'bl64_msg_show_info'
bl64_msg_show_input 'bl64_msg_show_input'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'bl64_msg_show_phase'
bl64_msg_show_task 'bl64_msg_show_task'
bl64_msg_show_subtask 'bl64_msg_show_subtask'
bl64_msg_show_separator
bl64_msg_show_lib_task 'bl64_msg_show_lib_task'
bl64_msg_show_lib_subtask 'bl64_msg_show_lib_subtask'
bl64_msg_show_lib_info 'bl64_msg_show_lib_info'
bl64_msg_show_batch_start 'bl64_msg_show_batch_start'
bl64_msg_show_batch_finish 0 'bl64_msg_show_batch_finish'
bl64_msg_show_batch_finish 1 'bl64_msg_show_batch_finish'

bl64_msg_set_format "$BL64_MSG_FORMAT_PLAIN"
bl64_msg_show_error 'bl64_msg_show_error'
bl64_msg_show_warning 'bl64_msg_show_warning'
bl64_msg_show_info 'bl64_msg_show_info'
bl64_msg_show_input 'bl64_msg_show_input'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'bl64_msg_show_phase'
bl64_msg_show_task 'bl64_msg_show_task'
bl64_msg_show_subtask 'bl64_msg_show_subtask'
bl64_msg_show_separator
bl64_msg_show_lib_task 'bl64_msg_show_lib_task'
bl64_msg_show_lib_subtask 'bl64_msg_show_lib_subtask'
bl64_msg_show_lib_info 'bl64_msg_show_lib_info'
bl64_msg_show_batch_start 'bl64_msg_show_batch_start'
bl64_msg_show_batch_finish 0 'bl64_msg_show_batch_finish'
bl64_msg_show_batch_finish 1 'bl64_msg_show_batch_finish'

bl64_msg_set_format "$BL64_MSG_FORMAT_HOST"
bl64_msg_show_error 'bl64_msg_show_error'
bl64_msg_show_warning 'bl64_msg_show_warning'
bl64_msg_show_info 'bl64_msg_show_info'
bl64_msg_show_input 'bl64_msg_show_input'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'bl64_msg_show_phase'
bl64_msg_show_task 'bl64_msg_show_task'
bl64_msg_show_subtask 'bl64_msg_show_subtask'
bl64_msg_show_separator
bl64_msg_show_lib_task 'bl64_msg_show_lib_task'
bl64_msg_show_lib_subtask 'bl64_msg_show_lib_subtask'
bl64_msg_show_lib_info 'bl64_msg_show_lib_info'
bl64_msg_show_batch_start 'bl64_msg_show_batch_start'
bl64_msg_show_batch_finish 0 'bl64_msg_show_batch_finish'
bl64_msg_show_batch_finish 1 'bl64_msg_show_batch_finish'

bl64_msg_set_format "$BL64_MSG_FORMAT_TIME"
bl64_msg_show_error 'bl64_msg_show_error'
bl64_msg_show_warning 'bl64_msg_show_warning'
bl64_msg_show_info 'bl64_msg_show_info'
bl64_msg_show_input 'bl64_msg_show_input'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'bl64_msg_show_phase'
bl64_msg_show_task 'bl64_msg_show_task'
bl64_msg_show_subtask 'bl64_msg_show_subtask'
bl64_msg_show_separator
bl64_msg_show_lib_task 'bl64_msg_show_lib_task'
bl64_msg_show_lib_subtask 'bl64_msg_show_lib_subtask'
bl64_msg_show_lib_info 'bl64_msg_show_lib_info'
bl64_msg_show_batch_start 'bl64_msg_show_batch_start'
bl64_msg_show_batch_finish 0 'bl64_msg_show_batch_finish'
bl64_msg_show_batch_finish 1 'bl64_msg_show_batch_finish'

bl64_msg_set_format "$BL64_MSG_FORMAT_CALLER"
bl64_msg_show_error 'bl64_msg_show_error'
bl64_msg_show_warning 'bl64_msg_show_warning'
bl64_msg_show_info 'bl64_msg_show_info'
bl64_msg_show_input 'bl64_msg_show_input'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'bl64_msg_show_phase'
bl64_msg_show_task 'bl64_msg_show_task'
bl64_msg_show_subtask 'bl64_msg_show_subtask'
bl64_msg_show_separator
bl64_msg_show_lib_task 'bl64_msg_show_lib_task'
bl64_msg_show_lib_subtask 'bl64_msg_show_lib_subtask'
bl64_msg_show_lib_info 'bl64_msg_show_lib_info'
bl64_msg_show_batch_start 'bl64_msg_show_batch_start'
bl64_msg_show_batch_finish 0 'bl64_msg_show_batch_finish'
bl64_msg_show_batch_finish 1 'bl64_msg_show_batch_finish'
