#!/usr/bin/env bash

. bin/dev-set
. "${DEVBL_BUILD_BASHLIB64}/${DEVBL_BUILD_BASHLIB64_FULL}"

bl64_msg_set_output "$BL64_MSG_OUTPUT_ASCII"
bl64_msg_show_error 'test'
bl64_msg_show_warning 'test'
bl64_msg_show_info 'test'
bl64_msg_show_input 'test'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'test'
bl64_msg_show_task 'test'
bl64_msg_show_subtask 'test'
bl64_msg_show_lib_task 'test'
_bl64_dbg_show 'test'
bl64_msg_show_batch_start 'test'
bl64_msg_show_batch_finish 0 'test'
bl64_msg_show_batch_finish 1 'test'

bl64_msg_set_format "$BL64_MSG_FORMAT_PLAIN"
bl64_msg_show_error 'test'
bl64_msg_show_warning 'test'
bl64_msg_show_info 'test'
bl64_msg_show_input 'test'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'test'
bl64_msg_show_task 'test'
bl64_msg_show_subtask 'test'
bl64_msg_show_lib_task 'test'
_bl64_dbg_show 'test'
bl64_msg_show_batch_start 'test'
bl64_msg_show_batch_finish 0 'test'
bl64_msg_show_batch_finish 1 'test'

bl64_msg_set_format "$BL64_MSG_FORMAT_HOST"
bl64_msg_show_error 'test'
bl64_msg_show_warning 'test'
bl64_msg_show_info 'test'
bl64_msg_show_input 'test'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'test'
bl64_msg_show_task 'test'
bl64_msg_show_subtask 'test'
bl64_msg_show_lib_task 'test'
_bl64_dbg_show 'test'
bl64_msg_show_batch_start 'test'
bl64_msg_show_batch_finish 0 'test'
bl64_msg_show_batch_finish 1 'test'

bl64_msg_set_format "$BL64_MSG_FORMAT_TIME"
bl64_msg_show_error 'test'
bl64_msg_show_warning 'test'
bl64_msg_show_info 'test'
bl64_msg_show_input 'test'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'test'
bl64_msg_show_task 'test'
bl64_msg_show_subtask 'test'
bl64_msg_show_lib_task 'test'
_bl64_dbg_show 'test'
bl64_msg_show_batch_start 'test'
bl64_msg_show_batch_finish 0 'test'
bl64_msg_show_batch_finish 1 'test'

bl64_msg_set_format "$BL64_MSG_FORMAT_CALLER"
bl64_msg_show_error 'test'
bl64_msg_show_warning 'test'
bl64_msg_show_info 'test'
bl64_msg_show_input 'test'; printf '%s\n' "[USER INPUT HERE]"
bl64_msg_show_phase 'test'
bl64_msg_show_task 'test'
bl64_msg_show_subtask 'test'
bl64_msg_show_lib_task 'test'
_bl64_dbg_show 'test'
bl64_msg_show_batch_start 'test'
bl64_msg_show_batch_finish 0 'test'
bl64_msg_show_batch_finish 1 'test'
