#!/usr/bin/env bash
#
# Skeleton for ad-hoc testing
#

#
# Imports
#

. test/lib/bash-setup.bash ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

#
# Globals
#

export TESTMANSH_TEST_SAMPLES

#
# Main
#

#
# Debugging Control
#

bl64_msg_all_enable_verbose
bl64_dbg_all_enable
#export BL64_LIB_CICD=YES

#
# Tests
#
# * Do not commit from this section below
#

# Enable for containers
#bl64_cnt_is_inside_container || { bl64_msg_show_error 'test must be run inside a container'; exit 1; }
