#!/usr/bin/env bash
#
# Skeleton for ad-hoc testing
#

clear

#
# Imports
#

. test/lib/adhoc-setup.bash ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

#
# Globals
#

#
# Main
#

#
# Debugging Control
#

export BL64_LIB_CICD=YES
#bl64_msg_all_enable_verbose
#bl64_dbg_all_enable
#bl64_dbg_lib_enable
#bl64_dbg_lib_task_enable

#
# Tests
#
# * Do not commit from this section below
#

# bl64_cnt_is_inside_container || exit 1
