#!/usr/bin/env bash
echo "======================================================================="
echo "WARING: this will be ran on the local machine, not in the container."
echo "======================================================================="

export TEST_ROOT="/opt/bl64"
export TEST_SRC="./build/prepare/project"

sudo rm -Rf "$TEST_ROOT" &&
sudo mkdir -p $TEST_ROOT &&
sudo cp -f $TEST_SRC/* "$TEST_ROOT" &&
sudo chmod 755 -f "$TEST_ROOT" "$TEST_ROOT"/*
