#!/usr/bin/env bash

. test/lib/adhoc-setup.bash ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

declare VARIABLE1='VALUE1'
declare VARIABLE2='VALUE2'
declare VARIABLE4=''

function level3() {
  bl64_dbg_runtime_show_callstack
}

function level2() {
  bl64_dbg_lib_show_info 'bl64_dbg_lib_show_info'
  bl64_dbg_lib_show_comments 'bl64_dbg_lib_show_comments'
  bl64_dbg_lib_show_vars 'VARIABLE1' 'VARIABLE2' 'VARIABLE3' 'VARIABLE4'
  level3
}

function level1() {
  bl64_dbg_lib_show_info 'bl64_dbg_lib_show_info'
  bl64_dbg_lib_show_comments 'bl64_dbg_lib_show_comments'
  bl64_dbg_lib_show_vars 'VARIABLE1' 'VARIABLE2' 'VARIABLE3' 'VARIABLE4'

  level2
}

bl64_dbg_all_enable
bl64_dbg_lib_show_info 'bl64_dbg_lib_show_info'
bl64_dbg_lib_show_comments 'bl64_dbg_lib_show_comments'
bl64_dbg_lib_show_vars 'VARIABLE1' 'VARIABLE2' 'VARIABLE3' 'VARIABLE4'

level1

bl64_dbg_all_disable
