#!/usr/bin/env bash

. test/lib/adhoc-setup.bash ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

function show() {
  local PARAMETER1='VALUE1'
  local PARAMETER2='VALUE2'
  local PARAMETER3=''
  local PARAMETER4='VALUE4'
  echo "------> BL64_MSG_VERBOSE=${BL64_MSG_VERBOSE}"
  bl64_msg_show_check 'bl64_msg_show_check'
  bl64_msg_show_error 'bl64_msg_show_error'
  bl64_msg_show_about
  bl64_msg_show_app_error 'bl64_msg_show_app_error'
  bl64_msg_show_lib_error 'bl64_msg_show_lib_error'
  bl64_msg_show_fatal 'bl64_msg_show_fatal'
  bl64_msg_show_warning 'bl64_msg_show_warning'
  bl64_msg_show_deprecated 'bl64_msg_show_deprecated'
  bl64_msg_show_info 'bl64_msg_show_info'
  bl64_msg_show_attention 'bl64_msg_show_attention'
  bl64_msg_show_setup "$BL64_VAR_DEFAULT" 'PARAMETER1' 'PARAMETER2' 'PARAMETER3' 'PARAMETER4' 'PARAMETER5'
  bl64_msg_show_input 'bl64_msg_show_input'
  printf '%s\n' "[USER INPUT HERE]"
  bl64_msg_show_phase 'bl64_msg_show_phase'
  bl64_msg_show_task 'bl64_msg_show_task'
  bl64_msg_show_subtask 'bl64_msg_show_subtask'
  bl64_msg_show_separator
  bl64_msg_show_lib_task 'bl64_msg_show_lib_task'
  bl64_msg_show_lib_subtask 'bl64_msg_show_lib_subtask'
  bl64_msg_show_lib_info 'bl64_msg_show_lib_info'
  bl64_msg_show_batch_start 'bl64_msg_show_batch_start'
  bl64_msg_show_batch_finish 0 'bl64_msg_show_batch_finish'
  bl64_msg_show_batch_finish 1 'bl64_msg_show_batch_finish'
}

echo "==[NONE]========================================================="
bl64_msg_all_disable_verbose
show

echo "==[APP]========================================================="
bl64_msg_app_enable_verbose
show

echo "==[LIB]========================================================="
bl64_msg_lib_enable_verbose
show

echo "==[ALL]========================================================="
bl64_msg_all_enable_verbose
show
