#!/usr/bin/env bash

. test/lib/adhoc-setup.bash ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

bl64_msg_help_set_usage '-a -b'
bl64_msg_help_set_about 'test script'
bl64_msg_help_set_description 'this is the description'
bl64_msg_help_set_parameters '-a: a parameter
-b: b parameter'

bl64_msg_show_separator 'bl64_msg_help_show'
bl64_msg_help_show

bl64_msg_show_separator 'bl64_msg_help_show_about'
bl64_msg_help_show_about

bl64_msg_show_separator 'bl64_msg_help_show_usage'
bl64_msg_help_show_usage
