#!/usr/bin/env bash

. bin/dev-set ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

  export BL64_LIB_CMD='1'
. "${DEV_PATH_BUILD_PREPARE}/${DEV_PACK_PROJECT_ASSETS_SA}" echo hello-world
