#!/usr/bin/env bash


. bin/dev-set ||
  { echo 'test:Error: unable to load test environment' 2>&1 && exit 1; }

. "${DEV_PATH_BUILD_PREPARE}/${DEV_PACK_PROJECT_ASSETS_SA}"

printf 'BL64_OS_FLAVOR: %s\n' "$BL64_OS_FLAVOR"
printf 'BL64_OS_DISTRO: %s\n' "$BL64_OS_DISTRO"
