#!/usr/bin/env bash

source './test/lib/bash-setup.bash' || exit $?

[[ "$(bl64_fmt_version_convert_to_major_minor '15.33.23')" == '15.33' ]] &&
[[ "$(bl64_fmt_version_convert_to_major_minor '1.3.2')" == '1.3' ]] &&
[[ "$(bl64_fmt_version_convert_to_major_minor '1.3')" == '1.3' ]]
