#!/usr/bin/env bash

source "${DEV_PATH_BUILD_PREPARE}/bashlib64.bash"

bl64_fmt_version_is_semver '20.30.4040' &&
bl64_fmt_version_is_semver '1.0.4' &&
! bl64_fmt_version_is_semver ' ' &&
! bl64_fmt_version_is_semver 'a.b.c' &&
! bl64_fmt_version_is_semver '1.0.4a'
