#!/usr/bin/env bash

source './test/lib/bash-setup.bash' || exit $?

bl64_fmt_version_is_semver '20.30.4040' &&
bl64_fmt_version_is_semver '1.0.4' &&
! bl64_fmt_version_is_semver ' ' &&
! bl64_fmt_version_is_semver 'a.b.c' &&
! bl64_fmt_version_is_semver '1.0.4a'
