#!/usr/bin/env bash

source './build/prepare/bashlib64.bash' || exit $?

bl64_fmt_version_is_major_minor '20.30' &&
! bl64_fmt_version_is_major_minor '20.30.4' &&
! bl64_fmt_version_is_major_minor '4'
