#######################################
# BashLib64 / Module / Globals / Interact with Kubernetes
#
# Version: 1.3.0
#######################################

# Optional module. Not enabled by default
export BL64_K8S_MODULE="$BL64_LIB_VAR_OFF"

export BL64_K8S_CMD_KUBECTL="$BL64_LIB_UNAVAILABLE"

export BL64_K8S_SET_VERBOSE_NONE="$BL64_LIB_UNAVAILABLE"
export BL64_K8S_SET_VERBOSE_NORMAL="$BL64_LIB_UNAVAILABLE"
export BL64_K8S_SET_VERBOSE_DEBUG="$BL64_LIB_UNAVAILABLE"
export BL64_K8S_SET_OUTPUT_JSON="$BL64_LIB_UNAVAILABLE"
export BL64_K8S_SET_OUTPUT_YAML="$BL64_LIB_UNAVAILABLE"
export BL64_K8S_SET_OUTPUT_TXT="$BL64_LIB_UNAVAILABLE"
export BL64_K8S_SET_OUTPUT_NAME="$BL64_LIB_UNAVAILABLE"

export BL64_K8S_VERSION_KUBECTL=''

export BL64_K8S_RESOURCE_NAMESPACE='namespace'
