#######################################
# BashLib64 / Module / Globals / Interact with Kubernetes
#######################################

# shellcheck disable=SC2034
{
  declare BL64_K8S_VERSION='3.1.4'

  declare BL64_K8S_MODULE='0'

  declare BL64_K8S_CMD_KUBECTL="$BL64_VAR_UNAVAILABLE"

  declare BL64_K8S_CFG_KUBECTL_OUTPUT=''
  declare BL64_K8S_CFG_KUBECTL_OUTPUT_JSON='j'
  declare BL64_K8S_CFG_KUBECTL_OUTPUT_YAML='y'

  declare BL64_K8S_SET_VERBOSE_NONE="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_VERBOSE_NORMAL="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_VERBOSE_DEBUG="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_OUTPUT_JSON="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_OUTPUT_YAML="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_OUTPUT_TXT="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_OUTPUT_NAME="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_DRY_RUN_SERVER="$BL64_VAR_UNAVAILABLE"
  declare BL64_K8S_SET_DRY_RUN_CLIENT="$BL64_VAR_UNAVAILABLE"

  declare BL64_K8S_VERSION_KUBECTL=''

  declare BL64_K8S_RESOURCE_NS='namespace'
  declare BL64_K8S_RESOURCE_SA='serviceaccount'
  declare BL64_K8S_RESOURCE_SECRET='secret'
}
