@test "bl64_lib_env: error constants are set" {
  . "$TESTMANSH_TEST_BATSCORE_SETUP"

# Parameters
  assert_equal $BL64_LIB_ERROR_PARAMETER_INVALID 3
  assert_equal $BL64_LIB_ERROR_PARAMETER_MISSING 4
  assert_equal $BL64_LIB_ERROR_PARAMETER_RANGE 5
  assert_equal $BL64_LIB_ERROR_PARAMETER_EMPTY 6

# Function operation
  assert_equal $BL64_LIB_ERROR_TASK_FAILED 10
  assert_equal $BL64_LIB_ERROR_TASK_BACKUP 11
  assert_equal $BL64_LIB_ERROR_TASK_RESTORE 12
  assert_equal $BL64_LIB_ERROR_TASK_TEMP 13
  assert_equal $BL64_LIB_ERROR_TASK_UNDEFINED 14

# Module operation
  assert_equal $BL64_LIB_ERROR_MODULE_SETUP_INVALID 20
  assert_equal $BL64_LIB_ERROR_MODULE_SETUP_MISSING 21

# OS
  assert_equal $BL64_LIB_ERROR_OS_NOT_MATCH 30
  assert_equal $BL64_LIB_ERROR_OS_TAG_INVALID 31
  assert_equal $BL64_LIB_ERROR_OS_INCOMPATIBLE 32
  assert_equal $BL64_LIB_ERROR_OS_BASH_VERSION 33

# External commands
  assert_equal $BL64_LIB_ERROR_APP_INCOMPATIBLE 40
  assert_equal $BL64_LIB_ERROR_APP_MISSING 41

# Filesystem
  assert_equal $BL64_LIB_ERROR_FILE_NOT_FOUND 50
  assert_equal $BL64_LIB_ERROR_FILE_NOT_READ 51
  assert_equal $BL64_LIB_ERROR_FILE_NOT_EXECUTE 52
  assert_equal $BL64_LIB_ERROR_DIRECTORY_NOT_FOUND 53
  assert_equal $BL64_LIB_ERROR_DIRECTORY_NOT_READ 54
  assert_equal $BL64_LIB_ERROR_PATH_NOT_RELATIVE 55
  assert_equal $BL64_LIB_ERROR_PATH_NOT_ABSOLUTE 56
  assert_equal $BL64_LIB_ERROR_PATH_NOT_FOUND 57
  assert_equal $BL64_LIB_ERROR_PATH_PRESENT 58

# IAM
  assert_equal $BL64_LIB_ERROR_PRIVILEGE_IS_ROOT 60
  assert_equal $BL64_LIB_ERROR_PRIVILEGE_IS_NOT_ROOT 61
  assert_equal $BL64_LIB_ERROR_USER_NOT_FOUND 62

# General
  assert_equal $BL64_LIB_ERROR_EXPORT_EMPTY 70
  assert_equal $BL64_LIB_ERROR_EXPORT_SET 71
  assert_equal $BL64_LIB_ERROR_OVERWRITE_NOT_PERMITED 72

}
