---
# Template: 1.1.0
name: "Lint / Bash / TestManSH"

on:
  push:
    branches:
      - "develop"
      - "feature/*"

jobs:
  lint-bash-testmansh:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run ShellCheck"
        run: "./lib/testmansh -t -c build/bashlib64.bash"
...
