---
# Template: 2.0.0
name: "Lint / Bash / TestManSH"

on:
  push:
    branches:
      - "develop"
      - "feature/*"

jobs:
  lint-bash-testmansh:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-lint"
...
