name: "Lint / Bash / TestManSH"

on:
  push:
    branches:
      - "develop"

jobs:
  lint_shellcheck:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Download testmansh"
        run: "curl -O https://raw.githubusercontent.com/serdigital64/testmansh/main/testmansh"

      - name: "Prepare build environment"
        run: "./bin/devbl-lib"

      - name: "Build app"
        run: "./bin/devbl-build -t"

      - name: "Run ShellCheck"
        run: "bash testmansh -t -c build/bashlib64.bash"
