---
# Template: 1.0.1
name: "Release"

env:
  DEV_CICD_DEBUG: ""
  DEV_LIB_GH_BIN: "gh"

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions: "write-all"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare dev environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-bashlib64"

      - name: "Build app for release"
        run: "./bin/dev-build-custom -r"

      - name: "Create distributable packages"
        run: "./bin/dev-pack"

      - name: "Create GitHub release"
        run: "./bin/dev-release ${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
