---
# Template: 1.1.2
name: "Test / Bash / TestManSH"

on:
  push:
    branches:
      - "feature/*"

jobs:
  test-batscore-alpine-3:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/alpine-3-bash-test:latest -c test/batscore/bash"

  test-batscore-almalinux-8:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/almalinux-8-bash-test:latest -c test/batscore/bash"

  test-batscore-almalinux-9:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/almalinux-8-bash-test:latest -c test/batscore/bash"

  test-batscore-rockylinux-8:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/rockylinux-8-bash-test:latest -c test/batscore/bash"

  test-batscore-rockylinux-9:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/rockylinux-8-bash-test:latest -c test/batscore/bash"

  test-batscore-rhel-8:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/rhel-8-bash-test:latest -c test/batscore/bash"

  test-batscore-centos-7:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/centos-7-bash-test:latest -c test/batscore/bash"

  test-batscore-centos-8:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/centos-8-bash-test:latest -c test/batscore/bash"

  test-batscore-centos-9:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/centos-9-bash-test:latest -c test/batscore/bash"

  test-batscore-oraclelinux-7:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/oraclelinux-7-bash-test:latest -c test/batscore/bash"

  test-batscore-oraclelinux-8:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/oraclelinux-8-bash-test:latest -c test/batscore/bash"

  test-batscore-fedora-33:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/fedora-33-bash-test:latest -c test/batscore/bash"

  test-batscore-fedora-34:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/fedora-34-bash-test:latest -c test/batscore/bash"

  test-batscore-fedora-35:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/fedora-35-bash-test:latest -c test/batscore/bash"

  test-batscore-fedora-36:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/fedora-36-bash-test:latest -c test/batscore/bash"

  test-batscore-fedora-37:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/fedora-36-bash-test:latest -c test/batscore/bash"

  test-batscore-debian-9:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/debian-9-bash-test:latest -c test/batscore/bash"

  test-batscore-debian-10:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/debian-10-bash-test:latest -c test/batscore/bash"

  test-batscore-debian-11:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/debian-11-bash-test:latest -c test/batscore/bash"

  test-batscore-ubuntu-204:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/ubuntu-20.4-bash-test:latest -c test/batscore/bash"

  test-batscore-ubuntu-214:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/ubuntu-21.4-bash-test:latest -c test/batscore/bash"

  test-batscore-ubuntu-224:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/ubuntu-22.4-bash-test:latest -c test/batscore/bash"

#  test-batscore-kubernetes:
#    runs-on: "ubuntu-latest"
#    steps:
#
#      - name: "Check out repository code"
#        uses: "actions/checkout@main"
#
#      - name: "Prepare build environment"
#        run: "./bin/dev-lib"
#
#      - name: "Build app"
#        run: "./bin/dev-build -t"
#
#      - name: "Run tests"
#        shell: 'script -q -e -c "bash {0}"'
#        run: "./lib/testmansh -b -o -e bash-test/oraclelinux-9-bash-test-k8s:latest -c test/batscore/kubernetes"

  test-batscore-terraform:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/oraclelinux-9-bash-test-terraform:latest -c test/batscore/terraform"

  test-batscore-mongodb:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/oraclelinux-9-bash-test-mongosh-6:latest -c test/batscore/mongodb"

  test-batscore-cloud:
      runs-on: "ubuntu-latest"
      steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/oraclelinux-9-bash-test-cloud:latest -c test/batscore/cloud"

  test-batscore-ansible:
      runs-on: "ubuntu-latest"
      steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Build app"
        run: "./bin/dev-build -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/oraclelinux-9-bash-test-ansible-2:latest -c test/batscore/ansible"
...
