---
# Template: 3.0.0
name: "Test / Bash / Non-OS"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-bsh"
      - "src/*-check"
      - "src/*-dbg"
      - "src/*-msg"
      - "src/*-rnd"
      - "src/*-ui"
      - "test/batscore/bash-non-os/**"

jobs:
  test-non-os:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-bashlib64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-build-bash"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-non-os"
...
