---
# Template: 3.2.1
name: "Test / TestManSH / Bash Non-OS"

env:
  DEV_CICD_DEBUG: ""

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-bsh"
      - "src/*-check"
      - "src/*-dbg"
      - "src/*-msg"
      - "src/*-rnd"
      - "src/*-ui"
      - "test/batscore/bash-non-os/**"

jobs:
  test-testmansh-bash-non-os:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        target:
          - "BASH_NON_OS"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare dev environment"
        run: "./bin/dev-lib-base"

      - name: "Build app"
        run: "./bin/dev-build-project"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-project &&
          ./bin/dev-test-testmansh "$DEV_TEST_TESTMANSH_CONTAINER_${{matrix.target}}" "$DEV_TEST_TESTMANSH_CASES_BASH_NON_OS"
...
