---
# Template: 3.0.0
name: "Test / Bash / OS"

env:
  DEV_CICD_DEBUG: ""

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-api-*"
      - "src/*-fmt-*"
      - "src/*-fs-*"
      - "src/*-iam-*"
      - "src/*-lib-*"
      - "src/*-os-*"
      - "src/*-rbac-*"
      - "src/*-rxtx-*"
      - "src/*-txt-*"
      - "src/*-vcs-*"
      - "test/batscore/bash-os/**"

jobs:
  test-os-:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        distro:
          - "fedora"
          - "redhat_a"
          - "redhat_b"
          - "debian"
          - "ubuntu"
          - "other"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-bashlib64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-build-custom -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-bash os ${{ matrix.distro }}"
