---
# Template: 3.4.0
name: "Test / TestManSH / Ansible"

env:
  DEV_CICD_DEBUG: ""
  BL64_LIB_CICD: "YES"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-ans-*"
      - "test/batscore/ansible/**"

jobs:
  test-testmansh-ansible:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        target:
          - "ANSIBLE"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Cache local tools"
        uses: "actions/cache@v4"
        with:
          path: ./lib
          key: ${{ runner.os }}-lib-cache
          restore-keys: |
            ${{ runner.os }}-lib-cache

      - name: "Prepare environment"
        run: "./bin/dev-lib-base"

      - name: "Download tools"
        run: "./bin/dev-lib-testmansh"

      - name: "Build app"
        run: "./bin/dev-build-project"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-project &&
          ./bin/dev-test-testmansh "$DEV_TEST_TESTMANSH_CONTAINER_${{matrix.target}}" "$DEV_TEST_TESTMANSH_CASES_ANSIBLE"
...
