---
# Template: 2.1.0
name: "Test / Bash / TestManSH / Ansible"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-ans-*"
      - "test/batscore/ansible/**"

jobs:
  test-batscore-os:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-ansible"
...
