---
# Template: 2.1.0
name: "Test / Bash / TestManSH / Terraform"

on:
  push:
    paths:
      - "src/*-tf-*"
      - "test/batscore/terraform/**"

jobs:
  test-batscore-os:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-terraform"
...
