---
# Template: 3.4.0
name: "Test / TestManSH / Container"

env:
  DEV_CICD_DEBUG: ""
  BL64_LIB_CICD: "YES"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-cnt-*"
      - "test/batscore/container/**"

jobs:
  test-testmansh-container:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        target:
          - "CONTAINER"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare environment"
        run: "./bin/dev-lib-base"

      - name: "Download tools"
        run: "./bin/dev-lib-testmansh"

      - name: "Build app"
        run: "./bin/dev-build-project"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: |
          source ./bin/dev-set &&
          source ./bin/dev-env-project &&
          ./bin/dev-test-testmansh "$DEV_TEST_TESTMANSH_CONTAINER_${{matrix.target}}" "$DEV_TEST_TESTMANSH_CASES_CONTAINER"
...
