---
# Template: 3.0.0
name: "Test / Bash / Kubernetes"

env:
  DEV_CICD_DEBUG: ""

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-hlm-*"
      - "src/*-k8s-*"
      - "test/batscore/kubernetes/**"

jobs:
  test-kubernetes:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib-installer64 && ./bin/dev-lib-bashlib64 && ./bin/dev-lib-testmansh"

      - name: "Build app"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-build-bash -t"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-bash kubernetes"
...
