---
# Template: 2.1.0
name: "Test / Bash / TestManSH / Non-OS"

on:
  push:
    paths:
      - "src/*-bsh"
      - "src/*-check"
      - "src/*-dbg"
      - "src/*-msg"
      - "src/*-rnd"
      - "src/*-ui"
      - "test/batscore/bash-non-os/**"

jobs:
  test-batscore-os:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-non-os"
...
