---
# Template: 2.2.0
name: "Test / Bash / TestManSH / Kubernetes"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "feature/**"
    paths:
      - "src/*-hlm-*"
      - "src/*-k8s-*"
      - "test/batscore/kubernetes/**"

jobs:
  test-kubernetes:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test-kubernetes"
...
